// <auto-generated />
using BookStoreSample.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookStoreSample.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookStoreSample.Model.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CoverUrl = "https://www.jarir.com/cdn-cgi/image/fit=contain,width=400,height=400/https://www.jarir.com/media//catalog/product/4/8/487333.jpg?1",
                            Price = 100.0,
                            Title = "Egypt"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CoverUrl = "https://www.jarir.com/cdn-cgi/image/fit=contain,width=400,height=400/https://www.jarir.com/media//catalog/product/3/5/352925.jpg?1",
                            Price = 200.0,
                            Title = "Mada'in Saleh"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CoverUrl = "https://www.jarir.com/cdn-cgi/image/fit=contain,width=400,height=400/https://www.jarir.com/media//catalog/product/4/8/480520.jpg?1",
                            Price = 300.0,
                            Title = "Sons of Sindbad"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CoverUrl = "https://www.jarir.com/cdn-cgi/image/fit=contain,width=400,height=400/https://www.jarir.com/media//catalog/product/4/7/473228.jpg?1",
                            Price = 500.0,
                            Title = "reSurface - Images of Women in The Rock Art of Saudi Arabia"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CoverUrl = "https://www.jarir.com/cdn-cgi/image/fit=contain,width=400,height=400/https://www.jarir.com/media//catalog/product/2/8/283208.jpg?1",
                            Price = 500.0,
                            Title = "Window Treatments for Every Room (Better Homes and Gardens)"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CoverUrl = "https://www.jarir.com/cdn-cgi/image/fit=contain,width=400,height=400/https://www.jarir.com/media//catalog/product/1/3/134547.jpg?1",
                            Price = 800.0,
                            Title = "Cast-Iron Architecture in America"
                        });
                });

            modelBuilder.Entity("BookStoreSample.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "History"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Art"
                        });
                });

            modelBuilder.Entity("BookStoreSample.Model.Book", b =>
                {
                    b.HasOne("BookStoreSample.Model.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
